name: Update Map

on:
  repository_dispatch:
    types: [update_map]
  workflow_dispatch:
    inputs:
      map_repo:
        description: "Map repository to use"
        required: true
        type: string

jobs:
  update-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          repository: zarSou9/trecursive
          token: ${{ secrets.AI_RESEARCH_MAPS_TOKEN }}
          path: trecursive

      - name: Checkout map repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.map_repo || inputs.map_repo }}
          path: map-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic

      - name: Run conversion scripts
        run: |
          python source-repo/create_map.py -p
          python source-repo/convert_meta.py -p --map-repo ${{ github.event.client_payload.map_repo || inputs.map_repo }}

      - name: Copy files to website repository
        run: |
          # Create directories if they don't exist
          mkdir -p trecursive/static/trees
          mkdir -p trecursive/src/lib/tree_settings

          # Copy the generated JSON file
          cp source-repo/map.json trecursive/static/trees/${PATH_NAME}.json

          # Copy the meta.json file
          cp source-repo/meta-converted.json trecursive/src/lib/tree_settings/${PATH_NAME}.json

      - name: Commit and push changes
        working-directory: trecursive
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add static/trees/${PATH_NAME}.json src/lib/tree_settings/${PATH_NAME}.json

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Action: Update ${PATH_NAME} files from source repository"
            git push
          fi
